name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: $(vmImage)
  steps:
  - checkout: self
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscriptionEndpoint: 21e067e8-d665-47d3-a1ed-20614ed1a820
      azureContainerRegistry: '{"loginServer":"testregistrydemo66.azurecr.io", "id" : "/subscriptions/45965b0a-923c-4a73-9052-05b40347a7ca/resourceGroups/rstest/providers/Microsoft.ContainerRegistry/registries/testregistrydemo66"}'
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: 21e067e8-d665-47d3-a1ed-20614ed1a820
      azureContainerRegistry: '{"loginServer":"testregistrydemo66.azurecr.io", "id" : "/subscriptions/45965b0a-923c-4a73-9052-05b40347a7ca/resourceGroups/rstest/providers/Microsoft.ContainerRegistry/registries/testregistrydemo66"}'
      action: Push an image
...
